services:
  db:
    image: postgres:15
    container_name: wellness_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wellness_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend   # looks for Dockerfile inside backend/
    container_name: wellness_backend
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/wellness_dev
    ports:
      - "8000:8000"

volumes:
  postgres_data:
